# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_im', '0002_auto_20190118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='内容'),
        ),
    ]
