# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_im', '0003_auto_20190118_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
            ],
        ),
    ]
